### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by Cybersoulja** [Oneseco-Media/.github#19]
- [x] Complete
- [x] @Cybersoulja created in Canva 

```[tasklist]
### Tasks
- [ ] https://github.com/Oneseco-Media/.github/issues/20
- [ ] https://github.com/Oneseco-Media/.github/issues/22
```

**Comment by Cybersoulja** [comment]
<details><summary>Details</summary>
<p>

[CLICK ME FOR MORE](https://shareg.pt/hXgnoCe)

</p>
</details>

**Comment by Cybersoulja** [comment]
I need @SapphireBaby to help design the EndGameTV Twitch site starting with the header

**Comment by SapphireBaby** [comment]
10-4
