### ISSUE TITLE
How can I persuade a newbie to log into Github daily?

### ISSUE THREAD

**Issue by Cybersoulja** [Oneseco-Media/.github#29]
### Discussed in https://github.com/orgs/Oneseco-Media/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **Cybersoulja** October 21, 2023</sup>
How do you motivate your team to use Github?

</div>

```[tasklist]
### Tasks
- [ ] Check discussion daily and create more conversation
- [ ] Utilize the Space Age Hustle Hashnode blog to answer questions publicly.
- [ ] Document the questions and answers for blog content
- [ ] Space Age Hustle players who contribute will get a role
```

**Comment by Cybersoulja** [comment]
I'm going to create a web3 app that uses the Blockchain to count, user check-in or logins daily. This can be a tool that's perfected internally and then sold to creators as a serverless function or api. 

- [ ] Research dApps the track user logins or service side events

- [ ] Since this is a simple one function project it should be easy to find a simple app already made

- [ ] Search for A WordPress, login counter that rewards users for daily check-in

- [ ] Weigh the pros and cons then proceeded with the best option

- [ ] Close this issue
